/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.InsuranceRole;

import business.organization.InsuranceOrganization;
import business.userAccount.UserAccount;
import business.workQueue.InjectVaccine;
import business.workQueue.PaymentRequest;
import business.workQueue.WorkRequest;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dev
 */
public class OutgoingPaymentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OutgoingPaymentJPanel
     */
    JPanel userProcessContainer;
    UserAccount ua;
    InsuranceOrganization o;

    public OutgoingPaymentJPanel(JPanel userProcessContainer, InsuranceOrganization o) {
        initComponents();
        this.userProcessContainer = userProcessContainer;

        this.o = o;
        populate();
    }

    public void populate() {
        DefaultTableModel dtm  =(DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0);
        for(WorkRequest wr: o.getWorkQueue().getWorkRequestList()){
            if(wr instanceof InjectVaccine){
                InjectVaccine pr= (InjectVaccine)wr;
                if(pr.getStatus()=="Bill forwarded to Insurance"){
                    Object row[] = new Object[7];
                    row[0] = pr.getP().getName();
                    row[1] = pr.getP().getInsurance_id();
                    row[2]= pr.getVd().getClinicName();
                    row[3] = pr.getRequestDate();
                    row[4] = pr.getAmount();
                    row[5] = pr.getP().getValidTill();
                    row[6] = pr;
                    dtm.addRow(row);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient", "Insurance #", "Pay to", "Date", "Total Amount", "Expiry", "Request ID"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 564;
        gridBagConstraints.ipady = 79;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(34, 23, 0, 34);
        add(jScrollPane1, gridBagConstraints);

        jButton2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton2.setText("Paid");
        jButton2.setBorder(new javax.swing.border.MatteBorder(null));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 97;
        gridBagConstraints.ipady = 45;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 227, 210, 0);
        add(jButton2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int s= jTable1.getSelectedRow();
        if(s<0){
            return;
        }
        else{
            WorkRequest wr = (WorkRequest)jTable1.getValueAt(s, 6);
            wr.setStatus("Bill Paid");
            wr.setResolveDate(new Date());
            populate();
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
