/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.cdcRole;

import business.Vaccine;
import business.enterprise.CdcEnterprise;
import business.enterprise.Enterprise;
import business.enterprise.PhdEnterprise;
import business.network.Network;
import business.organization.ClinicOrganization;
import business.organization.DistributorOrganization;
import business.organization.HospitalOrganization;
import business.organization.ManufactureOrganization;
import business.organization.Organization;
import business.workQueue.CallBack;
import javax.swing.JPanel;

/**
 *
 * @author Dev
 */
public class CallBackJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CallBackJPanel
     */
    JPanel userProcessContainer;
CdcEnterprise cdcEnterprise;
Network n;
   public  CallBackJPanel(JPanel userProcessContainer, CdcEnterprise cdcEnterprise, Network n) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.cdcEnterprise = cdcEnterprise;
       this.n=n;
       populate();
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
public void populate(){
    jComboBox1.removeAllItems();
    for (Organization o : cdcEnterprise.getOrganizationDirectory().getOrganizationList()) {
            if (o instanceof DistributorOrganization) {
                for (Organization o1 : o.getOrganizationDirectory().getOrganizationList()) {
                    if (o1 instanceof ManufactureOrganization) {
                        ManufactureOrganization mo = (ManufactureOrganization) o1;
                        for (Vaccine v : mo.getProductCatalog()) {

                            jComboBox1.addItem(v.getName());
                        }
                    }
                }
            }
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Vaccine");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        jScrollPane1.setViewportView(txtDesc);

        jLabel2.setText("Why?");

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButton1.setText("BroadCast >>");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String a = (String) jComboBox1.getSelectedItem();
       Vaccine vaccine=null;
       Boolean flag=false;
       for (Organization o : cdcEnterprise.getOrganizationDirectory().getOrganizationList()) {
            if (o instanceof DistributorOrganization) {
                for (Organization o1 : o.getOrganizationDirectory().getOrganizationList()) {
                    if (o1 instanceof ManufactureOrganization) {
                        ManufactureOrganization mo = (ManufactureOrganization) o1;
                        for (Vaccine v : mo.getProductCatalog()) {
                            if(v.getName()==a){
                                vaccine = v;
                                flag=true;
                                break;
                            }
                        }
                    }
                    if(flag)break;
                }
            }
             if(flag)break;
        }
       CallBack cb = new CallBack();
       cb.setVaccine(vaccine);
       cb.setDescription(txtDesc.getText());
       cb.setSender(cdcEnterprise);
       cb.setStatus("Sent");
       cdcEnterprise.getWorkQueue().getWorkRequestList().add(cb);
       for(Network state: n.getStateList()){
           for(Enterprise e: state.getEnterpriseDirectory().getEnterpriseList()){
               if(e instanceof PhdEnterprise){
                   for(Organization o: e.getOrganizationDirectory().getOrganizationList()){
                       if(o instanceof HospitalOrganization){
                           System.out.println(o.getName());
                           o.getWorkQueue().getWorkRequestList().add(cb);
                           for(Organization o1: o.getOrganizationDirectory().getOrganizationList()){
                               if(o1 instanceof ClinicOrganization){
                                   o1.getWorkQueue().getWorkRequestList().add(cb);
                               }
                           }
                       }
                   }
               }
           }
       }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton6;
    private javax.swing.JButton backJButton7;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDesc;
    // End of variables declaration//GEN-END:variables
}
