/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.cdcRole;
import business.Vaccine;
import business.enterprise.Enterprise;
import business.organization.DistributorOrganization;
import business.organization.ManufactureOrganization;
import business.organization.Organization;
import business.userAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author Dev
 */
public class ManageVaccineJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageVaccineJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;

    Enterprise e;

//String[] items = {"Funded", "Not Funded"};
//final JComboBox combo = new JComboBox(items);
    ManageVaccineJPanel(JPanel userProcessContainer, UserAccount account, Enterprise e) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.e = e;

//        TableColumn sportColumn = tblVaccine.getColumnModel().getColumn(2);
//
//        JComboBox comboBox = new JComboBox();
//        comboBox.addItem("Funded");
//        comboBox.addItem("Not Funded");
//        
//        comboBox.setSelectedIndex(1);
//        sportColumn.setCellEditor(new DefaultCellEditor(comboBox));
        populate();
        //String[] items = {"Funded","Not Funded"};

//throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
Action action = new AbstractAction(){
    public void actionPerformed(ActionEvent e)
    {
        TableCellListener tcl = (TableCellListener)e.getSource();
 //       System.out.println("Row   : " + tcl.getRow());
//        System.out.println("Column: " + tcl.getColumn());
//        System.out.println("Old   : " + tcl.getOldValue());
//        System.out.println("New   : " + tcl.getNewValue());
        
        Vaccine v = (Vaccine) tblVaccine.getValueAt(tcl.getRow(),0);
        if(tcl.getColumn()==4){
            v.setHospitalPrice(Integer.parseInt((String) tcl.getNewValue()));
            populate();
        }
         if(tcl.getColumn()==5){
            v.setPatientPrice(Integer.parseInt((String) tcl.getNewValue()));
            populate();
        }
    }
};


    public void populate() {
        DefaultTableModel dtm = (DefaultTableModel) tblVaccine.getModel();
        dtm.setRowCount(0);
        //tblVaccine.setAutoCreateRowSorter(true);
TableCellListener tcl = new TableCellListener(tblVaccine, action);
        for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
            if (o instanceof DistributorOrganization) {
                for (Organization o1 : o.getOrganizationDirectory().getOrganizationList()) {
                    if (o1 instanceof ManufactureOrganization) {
                        ManufactureOrganization mo = (ManufactureOrganization) o1;
                        for (Vaccine v : mo.getProductCatalog()) {

                            Object row[] = new Object[6];
                            row[0] = v;
                            row[1] = v.getName();
                            row[2] = v.getType();
                            row[3] = v.getPrice();
                            row[4] = v.getHospitalPrice();
                            row[5] = v.getPatientPrice();
                            dtm.addRow(row);
                        }
                    }
                }
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnViewDetails = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVaccine = new javax.swing.JTable();
        btnFunded = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        btnViewDetails.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnViewDetails.setText("View Details");
        btnViewDetails.setBorder(new javax.swing.border.MatteBorder(null));
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 61;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 37, 0, 0);
        add(btnViewDetails, gridBagConstraints);

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(74, 0, 80, 0);
        add(backJButton, gridBagConstraints);

        tblVaccine.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        tblVaccine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Type", "Manufacture Price", "Hospital Price", "Patient Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblVaccine);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 595;
        gridBagConstraints.ipady = 155;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(29, 0, 0, 0);
        add(jScrollPane2, gridBagConstraints);

        btnFunded.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnFunded.setText("Change toFederally Funded");
        btnFunded.setBorder(new javax.swing.border.MatteBorder(null));
        btnFunded.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFundedActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 57;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 38, 0, 0);
        add(btnFunded, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel10.setText("Manage Vaccine");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 52;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 104, 0, 0);
        add(jLabel10, gridBagConstraints);

        jButton2.setText("Export");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 35;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 39, 0, 0);
        add(jButton2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        int selected = tblVaccine.getSelectedRow();
        if (selected < 0) {
            return;
        } else {
            Vaccine d = (Vaccine) tblVaccine.getValueAt(selected, 0);
            ViewVaccineDetailsJPanel v = new ViewVaccineDetailsJPanel(userProcessContainer, d);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add("ViewVaccineDetails", v);
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void btnFundedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFundedActionPerformed
        int selected = tblVaccine.getSelectedRow();
        if (selected < 0) {
            return;
        } else {
            Vaccine d = (Vaccine) tblVaccine.getValueAt(selected, 0);
            d.setType("Federally Funded");
           
            populate();
        }
    }//GEN-LAST:event_btnFundedActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        int option = fc.showSaveDialog(ManageVaccineJPanel.this);
        if(option == JFileChooser.APPROVE_OPTION){
            String filename = fc.getSelectedFile().getName();
            String path = fc.getSelectedFile().getParentFile().getPath();

            int len = filename.length();
            String ext = "";
            String file = "";

            if(len > 4){
                ext = filename.substring(len-4, len);
            }

            if(ext.equals(".xls")){
                file = path + "\\" + filename; 
            }else{
                file = path + "\\" + filename + ".xls"; 
            }
            toExcel(tblVaccine, new File(file));
        }
    }//GEN-LAST:event_jButton2ActionPerformed
public void toExcel(JTable table, File file){
    try{
        TableModel model = table.getModel();
        FileWriter excel = new FileWriter(file);

        for(int i = 0; i < model.getColumnCount(); i++){
            excel.write(model.getColumnName(i) + "\t");
        }

        excel.write("\n");

        for(int i=0; i< model.getRowCount(); i++) {
            for(int j=0; j < model.getColumnCount(); j++) {
                excel.write(model.getValueAt(i,j).toString()+"\t");
            }
            excel.write("\n");
        }

        excel.close();

    }catch(IOException e){ System.out.println(e); }
   }

//    class CheckBoxCellRenderer implements TableCellRenderer {
//
//        JComboBox combo;
//
//        public CheckBoxCellRenderer(JComboBox comboBox) {
//            this.combo = new JComboBox();
//            for (int i = 0; i < comboBox.getItemCount(); i++) {
//                combo.addItem(comboBox.getItemAt(i));
//            }
//        }
//
//        public Component getTableCellRendererComponent(JTable jtable,
//                Object value,
//                boolean isSelected,
//                boolean hasFocus,
//                int row, int column) {
//            combo.setSelectedItem(value);
//
//            return combo;
//        }
//    }
//
//    class customEditor extends DefaultCellEditor {
//
//        public customEditor(JComboBox comboBox) {
//            super(comboBox);
//            //System.out.println("here");
//            comboBox.addItemListener(new ItemListener() {
//
//                @Override
//                public void itemStateChanged(ItemEvent e) {
//                    //System.out.println("here22");
//                    if (e.getStateChange() == ItemEvent.SELECTED) {
//                        //System.out.println(tblVaccine.getSelectedRow()); 
//                    }
//                    //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//                }
//            });
//        }
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnFunded;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblVaccine;
    // End of variables declaration//GEN-END:variables
}
