/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.guestLogin;

import business.EcoSystem;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Dev
 */
public class GuestLoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GuestLoginJPanel
     */
    JPanel container;
    EcoSystem system;
    public GuestLoginJPanel(JPanel container, EcoSystem system) {
        initComponents();
        this.container = container;
        this.system= system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnForHosp = new javax.swing.JButton();
        btnClinic = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        btnForHosp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnForHosp.setText("For Hospitals");
        btnForHosp.setBorder(new javax.swing.border.MatteBorder(null));
        btnForHosp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForHospActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 56;
        gridBagConstraints.ipady = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(106, 185, 0, 188);
        add(btnForHosp, gridBagConstraints);

        btnClinic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnClinic.setText("For Clinics");
        btnClinic.setBorder(new javax.swing.border.MatteBorder(null));
        btnClinic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClinicActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 72;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 185, 150, 188);
        add(btnClinic, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnForHospActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForHospActionPerformed
        HospitalGuestLoginJPanel h = new HospitalGuestLoginJPanel(container, system);
        CardLayout l = (CardLayout) container.getLayout();
        container.add("hospital_guest_login",h);
        l.next(container);
    }//GEN-LAST:event_btnForHospActionPerformed

    private void btnClinicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClinicActionPerformed
      ClinicGuestLoginJPanel h = new ClinicGuestLoginJPanel(container, system);
        CardLayout l = (CardLayout) container.getLayout();
        container.add("ClinicGuestLoginJPanel",h);
        l.next(container);
    }//GEN-LAST:event_btnClinicActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClinic;
    private javax.swing.JButton btnForHosp;
    // End of variables declaration//GEN-END:variables
}
