/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ManufactureRole;

import business.enterprise.CdcEnterprise;
import userInterface.DistributorRole.*;
import userInterface.HospitalRole.*;
import business.enterprise.Enterprise;
import business.organization.DistributorOrganization;
import business.organization.HospitalOrganization;
import business.organization.ManufactureOrganization;
import business.organization.Organization;
import business.organization.ProviderOrganization;
import business.workQueue.ClinicOrderRequest;
import business.workQueue.DistributorVaccineOrder;
import business.workQueue.WorkRequest;
import java.awt.Button;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dev
 */
public class ManageManufacturerOrderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageClinicOrderJPanel
     */
    CdcEnterprise enterprise;
    JPanel userProcessContainer;
    ManufactureOrganization o;
  DistributorOrganization distributorOrg;
    public ManageManufacturerOrderJPanel(JPanel userProcessContainer, ManufactureOrganization o,  DistributorOrganization distributorOrg, CdcEnterprise enterprise) {
        initComponents(); //To change body of generated methods, choose Tools | Templates.
        this.userProcessContainer = userProcessContainer;
        this.o = o;
        this.enterprise = enterprise;
        this.distributorOrg = distributorOrg;
        populate();
    }

    public void populate() {
        DefaultTableModel dtm = (DefaultTableModel) tblClinicOrders.getModel();
        dtm.setRowCount(0);

        for (WorkRequest w : o.getWorkQueue().getWorkRequestList()) {
            if (w instanceof DistributorVaccineOrder) {
                DistributorVaccineOrder c = (DistributorVaccineOrder) w;
                if (c.getStatus() == "Forwarded to Manufacturer") {
                    Object row[] = new Object[2];
                    row[0] = c;
                    row[1] = c.getOrder().getTimestamp();
                    dtm.addRow(row);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        tblClinicOrders = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        tblClinicOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Order ID", "Order Date"
            }
        ));
        jScrollPane1.setViewportView(tblClinicOrders);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 677;
        gridBagConstraints.ipady = 94;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(56, 19, 0, 42);
        add(jScrollPane1, gridBagConstraints);

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton1.setText("View Order");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 279, 183, 0);
        add(jButton1, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel1.setText("View Orders");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 293, 0, 0);
        add(jLabel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int s = tblClinicOrders.getSelectedRow();
        if (s < 0) {
            return;
        } else {
            DistributorVaccineOrder cor = (DistributorVaccineOrder) tblClinicOrders.getValueAt(s, 0);
            ViewOrderJPanel h = new ViewOrderJPanel(userProcessContainer, cor, o, distributorOrg,enterprise);
            CardLayout l = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add("disvieworder", h);
            l.next(userProcessContainer);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClinicOrders;
    // End of variables declaration//GEN-END:variables
}
