/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ShipperRole;

import business.organization.HospitalOrganization;
import business.organization.ShipperOrganization;
import business.organization.WarehouseOrganization;
import business.userAccount.UserAccount;
import business.workQueue.DistributorVaccineOrder;
import business.workQueue.ShipmentRequest;
import business.workQueue.WarehouseShipmentRequest;
import business.workQueue.WorkRequest;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dev
 */
public class ShipmentRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ShipmentRequestJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    ShipperOrganization shipperOrganization;

    ShipmentRequestJPanel(JPanel userProcessContainer, ShipperOrganization shipperOrganization) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.shipperOrganization = shipperOrganization;
        populate();
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void populate(){
    DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
    dtm.setRowCount(0);
    for(WorkRequest w: shipperOrganization.getWorkQueue().getWorkRequestList()){
       
          //  ShipmentRequest sr = (ShipmentRequest)w;
            if(w.getStatus()=="Forwarded to Shipment" || w.getStatus()=="Picked Up"){
                Object row[] = new Object[5];
                row[0] = w;
                row[1] =w.getRequestDate();
              
                row[2] =w.getStatus();
                row[3] = w.getSender().getName();
                //System.out.println(w.getClass());
                if(w instanceof WarehouseShipmentRequest){
                    WarehouseShipmentRequest ws = (WarehouseShipmentRequest) w;
                    if(ws.getCor().getHospOrg()==null){
                        HospitalOrganization ho = (HospitalOrganization) ws.getCor().getSender();
                    row[4] = ho.getStreet()+", "+ho.getState()+", "+ho.getPin();
                    }
                    else{
                    HospitalOrganization ho = ws.getCor().getHospOrg();
                    row[4] = ho.getStreet()+", "+ho.getState()+", "+ho.getPin();
                    }
                }
                else if(w instanceof ShipmentRequest){
                    ShipmentRequest sr = (ShipmentRequest)w;
                    DistributorVaccineOrder dvo = (DistributorVaccineOrder)sr.getDvo();
                    WarehouseOrganization wo =(WarehouseOrganization)dvo.getWarehouse();
                    //System.out.println(wo);
                    row[4] = wo.getStreet()+", "+wo.getCity()+", "+wo.getState()+", "+wo.getPin();
                }
                dtm.addRow(row);
            }
       
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Request ID", " Date", "Status", "Sender", "Receiverl"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 617;
        gridBagConstraints.ipady = 171;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(11, 24, 0, 10);
        add(jScrollPane1, gridBagConstraints);

        jButton1.setText("Pick Up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 46;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 73, 176, 0);
        add(jButton1, gridBagConstraints);

        jButton2.setText("Ship");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 77;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 18, 176, 0);
        add(jButton2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 103;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(48, 4, 0, 0);
        add(jDateChooser1, gridBagConstraints);

        jLabel1.setText("Delivery Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(54, 58, 0, 0);
        add(jLabel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int s= jTable1.getSelectedRow();
        if(s<0){
            return;
        }
        else{
            WorkRequest wr=(WorkRequest)jTable1.getValueAt(s, 0);
            wr.setStatus("Picked Up");
            if(wr instanceof WarehouseShipmentRequest){
                WarehouseShipmentRequest wsr = (WarehouseShipmentRequest)wr;
                wsr.getCor().getOrder().setStatus("In Shipment");
            }
            populate();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int s= jTable1.getSelectedRow();
        if(s<0){
            return;
        }
        else{
            WorkRequest wr=(WorkRequest)jTable1.getValueAt(s, 0);
            wr.setStatus("In Shipment");
               if(wr instanceof WarehouseShipmentRequest){
                WarehouseShipmentRequest wsr = (WarehouseShipmentRequest)wr;
                wsr.getCor().getOrder().setStatus("Shipped");
                wsr.getCor().getOrder().setShippingdate(jDateChooser1.getDate());
            }
            populate();
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
