/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ProviderRole;

import business.enterprise.Enterprise;
import business.organization.Organization;
import business.organization.ProviderOrganization;
import business.workQueue.AddNewHospitalRequest;
import business.workQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;




/**
 *
 * @author Dev
 */
public class HospitalJoinRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HospitalJoinRequestJPanel
     */
   // JPanel myContainer;
    JPanel userProcessContainer;
    Enterprise e;
    ProviderOrganization providerOrganization;
    public HospitalJoinRequestJPanel(JPanel userProcessContainer, ProviderOrganization providerOrganization, Enterprise e) {
        initComponents();
        //this.myContainer = myContainer;
       this.providerOrganization = providerOrganization;
        this.userProcessContainer = userProcessContainer;
        this.e=e;
        populate();
    }
public void populate(){
    DefaultTableModel dtm = (DefaultTableModel) tblReq.getModel();
    dtm.setRowCount(0);
    for(WorkRequest w: providerOrganization.getWorkQueue().getWorkRequestList()){
        if (w instanceof AddNewHospitalRequest){
            AddNewHospitalRequest a= (AddNewHospitalRequest)w;
            Object row[] = new Object[3];
            row[0] = a;
            row[1] = a.getOrganization();
            row[2] = a.getRequestDate();
            
            dtm.addRow(row);
        }
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReq = new javax.swing.JTable();
        btnDetails = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("New Joining Request");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 38, 0, 0);
        add(jLabel1, gridBagConstraints);

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(51, 41, 0, 0);
        add(backJButton, gridBagConstraints);

        tblReq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Dates"
            }
        ));
        jScrollPane1.setViewportView(tblReq);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 560;
        gridBagConstraints.ipady = 115;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 10);
        add(jScrollPane1, gridBagConstraints);

        btnDetails.setText("Details");
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 134, 0, 0);
        add(btnDetails, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
       int selected = tblReq.getSelectedRow();
       if(selected <0){
           return;
       }
       else{
       WorkRequest w= (WorkRequest) tblReq.getValueAt(selected, 0);
       HospitalDetailsJPanel h= new HospitalDetailsJPanel(userProcessContainer,w,e,providerOrganization);
       CardLayout l = (CardLayout) userProcessContainer.getLayout();
       userProcessContainer.add("new_hosp_details",h);
       l.next(userProcessContainer);
       }
    }//GEN-LAST:event_btnDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReq;
    // End of variables declaration//GEN-END:variables
}
