/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.DistributorRole;

import userInterface.ClinicRole.*;
import business.Order;
import business.OrderItem;
import java.awt.CardLayout;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

    

/**
 *
 * @author admin
 */
public class HistoryDetails extends javax.swing.JPanel {

    
    JPanel userProcessContainer;
    Order order;
    public HistoryDetails(JPanel userProcessContainer, Order order) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.order = order;
        populate();
    }
public void populate()
{
    Border border = null;
    if(order.getStatus()=="Forwarded to Hospital"){
    progressBar.setValue(0);
     border = BorderFactory.createTitledBorder("Forwarded to Hospital...");
    }
    else if(order.getStatus()=="Forwarded to Provider"){
    progressBar.setValue(15);
     border = BorderFactory.createTitledBorder("Forwarded to Provider...");
    }
    else if(order.getStatus()=="Forwarded to State Dept"){
    progressBar.setValue(30);
     border = BorderFactory.createTitledBorder("Forwarded to State Dept...");
    }
    else if(order.getStatus()=="Forwarded to CDC"){
    progressBar.setValue(45);
     border = BorderFactory.createTitledBorder("Forwarded to CDC...");
    }
    else if(order.getStatus()=="Forwarded to Distributor"){
    progressBar.setValue(60);
     border = BorderFactory.createTitledBorder("Forwarded to Distributor...");
    }
    else if(order.getStatus()=="Shipped"){
    progressBar.setValue(80);
     border = BorderFactory.createTitledBorder("In Shipment...");
    }
    else if(order.getStatus()=="Complete"){
    progressBar.setValue(100);
     border = BorderFactory.createTitledBorder("Complete...");
    }
    progressBar.setStringPainted(true);
    
    progressBar.setBorder(border);
    DefaultTableModel modal = (DefaultTableModel) tblHistory.getModel();
        modal.setRowCount(0);

    for(OrderItem oi: order.getOrder()) {
               Object row[] = new Object[4];
                row[0] = oi.getProduct().getName();
                row[1] = oi.getQuantity();
                row[2] = oi.getProduct().getHospitalPrice();
               row[3] = oi.getQuantity() * oi.getProduct().getHospitalPrice();
                modal.addRow(row);
}
}
/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHistory = new javax.swing.JTable();
        progressBar = new javax.swing.JProgressBar();

        setBackground(new java.awt.Color(255, 255, 255));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product", "Quantity", "Price", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblHistory);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(btnBack))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JTable tblHistory;
    // End of variables declaration//GEN-END:variables
}
