/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.HospitalRole;

import business.Vaccine;
import business.enterprise.CdcEnterprise;
import business.organization.DistributorOrganization;
import business.organization.HospitalOrganization;
import business.organization.ManufactureOrganization;
import business.organization.Organization;
import business.workQueue.AdverseEventReport;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dev
 */
public class ReportEventJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportEventJPanel
     */
    JPanel userProcessContainer;
    HospitalOrganization o;
    CdcEnterprise parentEnt;

    public ReportEventJPanel(JPanel userProcessContainer, HospitalOrganization o, CdcEnterprise parentEnt) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.o = o;
        this.parentEnt = parentEnt;
        populate();
        // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void populate() {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        for (Organization o : parentEnt.getOrganizationDirectory().getOrganizationList()) {
            if (o instanceof DistributorOrganization) {
                for (Organization o1 : o.getOrganizationDirectory().getOrganizationList()) {
                    if (o1 instanceof ManufactureOrganization) {
                        ManufactureOrganization mo = (ManufactureOrganization) o1;
                        for (Vaccine v : mo.getProductCatalog()) {
                            Object row[] = new Object[2];
                            row[0] = v;
                            row[1] = v.getName();
                            dtm.addRow(row);
                        }
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        jScrollPane1.setViewportView(txtDesc);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 193, 240, 125));

        jLabel2.setText("Description");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        jButton1.setText("Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 348, 99, 41));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Vaccine ID", "Name"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 11, -1, 130));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int s = jTable1.getSelectedRow();
        if (s < 0) {
            return;
        } else {
            AdverseEventReport aer = new AdverseEventReport();
            aer.setVaccine((Vaccine) jTable1.getValueAt(s, 0));
            aer.setDescription(txtDesc.getText());
            aer.setSender(o);
            aer.setReceiver(parentEnt);
            aer.setStatus("Pending");
            o.getWorkQueue().getWorkRequestList().add(aer);
            parentEnt.getWorkQueue().getWorkRequestList().add(aer);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea txtDesc;
    // End of variables declaration//GEN-END:variables
}
